### ISSUE TITLE
build目录下的文件如何启用压缩

### ISSUE THREAD

**Issue by alex-my** [alibaba/beidou#118]
服务器上用了`nginx`，且启用了`Gzip`
<img width="599" alt="1" src="https://user-images.githubusercontent.com/3118939/48660183-90332680-ea98-11e8-8bdc-7ea194a9200f.png">

用`PageSpeed`测试的时候，提示我`build`下的`app.js`可以启用压缩

<img width="645" alt="2" src="https://user-images.githubusercontent.com/3118939/48660190-b22ca900-ea98-11e8-9fea-1cd5f0c07a53.png">
<img width="479" alt="3" src="https://user-images.githubusercontent.com/3118939/48660191-b22ca900-ea98-11e8-909f-cee39f16bcb8.png">

请教下，这个该如何压缩。

**Comment by ahungrynoob** [comment]
koa有相关gzip插件、然后配合egg.js框架搭建一下就ok

**Comment by alex-my** [comment]
> koa有相关gzip插件、然后配合egg.js框架搭建一下就ok

我看了看有一个`koa-compress`，文档中中间件部分有看到，这个是对返回的内容进行压缩。app.js 是打包出来的。
<img width="633" alt="4" src="https://user-images.githubusercontent.com/3118939/48660347-1a7c8a00-ea9b-11e8-9399-077bc89401c9.png">
（另外也不知道为啥我的`app.js`体积那么大，用了`antd`）

**Comment by ahungrynoob** [comment]
用了antd的话，需要注意babel-import-blugin的配置，这个插件是按需加载的插件，配置错误的话会全部打包进去。另外koa-gzip并不会减少打包体积，查看你截图的response headers发现并没有content-encoding

**Comment by alex-my** [comment]
我再找找资料看看为什么那些文件没有启用压缩。

关于`antd`，以前也询问过的，#72

我模仿这做了以下配置:

`config.default.js`:

```text
'use strict';

const path = require('path');

module.exports = {
  isomorphic: {
    babel: {
      plugins: [
        require.resolve('babel-plugin-transform-decorators-legacy'),
        require.resolve('babel-plugin-dynamic-import-node'),
        [
          require.resolve('babel-plugin-import-inspector'),
          {
            serverSideRequirePath: true,
          },
        ],
        [
          require.resolve('babel-plugin-import'),
          {
            libraryName: 'antd',
            // 对比 #72 少了这句，我这会报错，错误见下方
            //  libraryDirectory: 'es'
            style: 'css',
          },
        ],
      ],
      extensions: ['.js', '.jsx'],
    },
  },
  webpack: {
    custom: {
      configPath: path.join(__dirname, './webpack.config.js'),
    },
  },
  ...
};
```

`webpack.config.js`:

```text
'use strict';

const path = require('path');

module.exports = (app, defaultConfig, dev) => {
  defaultConfig.externals = {
    react: 'React',
    'react-dom': 'ReactDOM',
    antd: true,
  };

  defaultConfig.resolve = {
    extensions: ['.json', '.js', '.jsx'],
  };

  for (const loader of defaultConfig.module.rules) {
    if (loader.test.test('.jsx') && loader.test.test('.js')) {
      if (!Array.isArray(loader.use.options.plugins)) {
        loader.use.options.plugins = [];
      }
      loader.use.options.babelrc = false;
      loader.use.options.cacheDirectory = dev;
      loader.use.options.compact = !dev;
      loader.use.options.highlightCode = true;
      loader.use.options.plugins.push(
        // 使用 @
        require.resolve('babel-plugin-transform-decorators-legacy'),
        // 自动扫描 react-intl 定义的语句, 不用专门去写 json 文件
        [
          'react-intl',
          {
            messagesDir: 'lang/.messages/',
            enforceDescriptions: false,
          },
        ],
        require.resolve('babel-plugin-dynamic-import-node'),
        [
          require.resolve('babel-plugin-import-inspector'),
          {
            serverSideRequirePath: true,
          },
        ],
        // 按需加载 antd 组件
        [
          require.resolve('babel-plugin-import'),
          {
            libraryName: 'antd',
            style: 'true',
          },
        ],
      );
      break;
    }
  }

  return defaultConfig;
};
```
添加了 `libraryDirectory: 'es'`，页面请求的时候会报错:

```text
2018-11-17 20:19:36,746 ERROR 74984 [-/127.0.0.1/-/320ms GET /] nodejs.SyntaxError: Unexpected identifier
(function (exports, require, module, __filename, __dirname) { import _extends from 'babel-runtime/helpers/extends';
                                                                     ^^^^^^^^

SyntaxError: Unexpected identifier
    at new Script (vm.js:73:7)
    at createScript (vm.js:245:10)
    at Object.runInThisContext (vm.js:297:10)
    at Module._compile (internal/modules/cjs/loader.js:657:28)
    at Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/alex/MyWork/webjs/app/node_modules/babel-register/lib/node.js:152:7)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
```

-----
如果我把两个配置文件中`babel-plugin-import`都注释了，文件就小很多了

```text
# 有 babel-plugin-import 时：

Hash: 0480d3dfb4210ee9188c
Version: webpack 3.12.0
Time: 6268ms
                      Asset       Size  Chunks                    Chunk Names
app.js?0480d3dfb4210ee9188c    1.11 MB       0  [emitted]  [big]  app
                manifest.js  805 bytes       1  [emitted]         manifest
                    app.css   70 bytes       0  [emitted]         app
   [0] external "React" 42 bytes {0} [not cacheable]
  [16] external "ReactDOM" 42 bytes {0} [not cacheable]
  [49] ./utils/logger.js 884 bytes {0} [built]
  [89] ./node_modules/react-router-dom/es/index.js 1.01 kB {0} [built]
 [106] ./node_modules/mobx-react/index.module.js 48.4 kB {0} [built]
 [152] ./constants/global-config.js 172 bytes {0} [built]
 [170] ./node_modules/react-loadable/lib/index.js 8.55 kB {0} [built]
 [229] ./utils/cookie.js 1.98 kB {0} [built]
 [232] multi ./client/pages/app/index.jsx 28 bytes {0} [built]
 [233] ./client/pages/app/index.jsx 4.48 kB {0} [built]
 [234] ./node_modules/react-router/es/index.js 723 bytes {0} [built]
 [254] ./client/layout/index.jsx 7.53 kB {0} [built]
 [366] ./client/components/layout/index.jsx 2.18 kB {0} [built]
 [509] ./client/pages/app/routes.jsx 2.5 kB {0} [built]
 [533] ./client/stores/index.js 1.26 kB {0} [built]
    + 559 hidden modules

Build finished


# 无 babel-plugin-import 时：

Hash: 6841a49eeb5a258c016e
Version: webpack 3.12.0
Time: 5186ms
                      Asset       Size  Chunks                    Chunk Names
app.js?6841a49eeb5a258c016e     419 kB       0  [emitted]  [big]  app
                manifest.js  805 bytes       1  [emitted]         manifest
                    app.css   70 bytes       0  [emitted]         app
   [2] external "React" 42 bytes {0} [not cacheable]
  [33] ./utils/logger.js 884 bytes {0} [built]
  [61] ./node_modules/react-router-dom/es/index.js 1.01 kB {0} [built]
  [72] ./node_modules/mobx-react/index.module.js 48.4 kB {0} [built]
  [98] ./constants/global-config.js 172 bytes {0} [built]
 [102] external "ReactDOM" 42 bytes {0} [not cacheable]
 [116] ./node_modules/react-loadable/lib/index.js 8.55 kB {0} [built]
 [142] ./utils/cookie.js 1.98 kB {0} [built]
 [145] multi ./client/pages/app/index.jsx 28 bytes {0} [built]
 [146] ./client/pages/app/index.jsx 4.48 kB {0} [built]
 [147] ./node_modules/react-router/es/index.js 723 bytes {0} [built]
 [167] ./client/layout/index.jsx 7.53 kB {0} [built]
 [279] ./client/components/layout/index.jsx 2.14 kB {0} [built]
 [308] ./client/pages/app/routes.jsx 2.5 kB {0} [built]
 [317] ./client/stores/index.js 1.26 kB {0} [built]
    + 343 hidden modules

Build finished
```

我再查查资料看看。

**Comment by ahungrynoob** [comment]
首先这个报错原因是：isomorphic是给node端做配置用的，node不支持es导入方式，仅支持commonjs方式，你把该配置项去除后antd默认以lib目录导出也就是commonjs方式。
```javascript
// 对比 #72 少了这句，我这会报错，错误见下方
            //  libraryDirectory: 'es'
```
另外有个疑问：项目根目录下是否有.babelrc文件
最后有个建议，你可以试下：去除antd:true这个外置变量，可能会导致antd的一些代码不参与编译打包
```javascript
defaultConfig.externals = {
    react: 'React',
    'react-dom': 'ReactDOM',
    antd: true,
  };
```

**Comment by alex-my** [comment]
`build/app.js`没有被压缩的原因是：

在`nginx`中的`gzip`配置不正确。

改为：

```text
gzip_types text/html text/plain application/x-javascript application/javascript text/css;
```

就会被压缩了。

[所有类型点这里](http://www.w3school.com.cn/media/media_mimeref.asp)

压缩后小了很多

<img width="785" alt="6" src="https://user-images.githubusercontent.com/3118939/48661754-21fb5d80-eab2-11e8-8a0c-da6f5c2d03f7.png">

@ahungrynoob 十分感谢耐心解答。明天我再看看`antd`按需打包，上了一天的班，眼睛干涩的要命。
