### ISSUE TITLE
Egg V2.3.0 有BUG

### ISSUE THREAD

**Issue by andylei18** [alibaba/beidou#25]
如果我单纯升级Egg 的版本 会导致有BUG！
升级原因:   Egg2比Egg1性能提升30%！

错误信息如下:
{
message: ""string" must be a string, Buffer, or ArrayBuffer",
stack: "TypeError: "string" must be a string, Buffer, or ArrayBuffer at Function.byteLength (buffer.js:481:11) at respond (/Users/dinglei/Documents/work/Code/ald/node_modules/koa/lib/application.js:246:25) at handleResponse (/Users/dinglei/Documents/work/Code/ald/node_modules/koa/lib/application.js:148:34) at <anonymous>",
name: "TypeError",
status: 500
}

**Comment by andylei18** [comment]
我理解 北斗 的解决方案 是结合Egg 稳定的Node服务做Client端的单向拓展，把webpack,router,react,ssr 分别做成plugin的方式维护并解耦

**Comment by devrsi0n** [comment]
beidou 更新到 egg@2 已经提交到 develop 分支，milestone 1.0.0 发布后就默认支持 egg@2 以上。
