### ISSUE TITLE
beidou init 报错

### ISSUE THREAD

**Issue by Leotw** [alibaba/beidou#33]
![image](https://user-images.githubusercontent.com/12053096/37036648-44591534-218b-11e8-989e-1160cdeb802d.png)

您好，我在进行脚手架初始化时报错，这里是具体错误：
downloading: http://registry.npm.taobao.org/beidou-example-redux/download/beidou-example-redux-0.3.5.tgz
/Users/tiwenleo/.nvm/versions/node/v8.5.0/lib/node_modules/beidou-cli/lib/commands/init.js:315
          const extracter = tar.Extract({ path: saveDir, strip: 1 });
                                ^
TypeError: tar.Extract is not a function
    at urllib.request (/Users/tiwenleo/.nvm/versions/node/v8.5.0/lib/node_modules/beidou-cli/lib/commands/init.js:315:33)
    at done (/Users/tiwenleo/.nvm/versions/node/v8.5.0/lib/node_modules/beidou-cli/node_modules/urllib/lib/urllib.js:478:5)
    at ClientRequest.onResponse (/Users/tiwenleo/.nvm/versions/node/v8.5.0/lib/node_modules/beidou-cli/node_modules/urllib/lib/urllib.js:584:14)
    at Object.onceWrapper (events.js:316:30)
    at emitOne (events.js:115:13)
    at ClientRequest.emit (events.js:210:7)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:565:21)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:116:23)
    at TLSSocket.socketOnData (_http_client.js:454:20)
    at emitOne (events.js:115:13)

**Comment by devrsi0n** [comment]
请通过 `npm install beidou-cli@next -g` 安装最新的 `beidou-cli` 版本。

**Comment by Leotw** [comment]
嗯，非常感谢，已经没问题了。。有空可以更新一下文档😄
