### ISSUE TITLE
fetch 请求

### ISSUE THREAD

**Issue by 18613109040** [alibaba/beidou#37]
我要如何在项目中调用fetch 
componentWillMount() {
        fetch('xxxx',{
            method:"GET"
        })
}
服务端一直出错
018-04-11 15:45:54,740 ERROR 16244 nodejs.unhandledRejectionError: only absolute urls are supported
    at D:\beidou-master\examples\with-react-router\node_modules\_node-fetch@1.7.3@node-fetch\index.js:54:10
    at Promise (<anonymous>)
    at new Fetch (D:\beidou-master\examples\with-react-router\node_modules\_node-fetch@1.7.3@node-fetch\index.js:49:9)
    at Fetch (D:\beidou-master\examples\with-react-router\node_modules\_node-fetch@1.7.3@node-fetch\index.js:37:10)
    at module.exports (D:\beidou-master\examples\with-react-router\node_modules\_isomorphic-fetch@2.2.1@isomorphic-fetch\fetch-npm-node.js:8:19)
    at Home.componentWillMount (D:/beidou-master/examples/with-react-router/client/containers/Home/index.jsx:15:9)
    at processChild (D:\beidou-master\examples\with-react-router\node_modules\_react-dom@16.3.1@react-dom\cjs\react-dom-server.node.development.js:2158:16)
    at resolve (D:\beidou-master\examples\with-react-router\node_modules\_react-dom@16.3.1@react-dom\cjs\react-dom-server.node.development.js:2052:5)
    at ReactDOMServerRenderer.render (D:\beidou-master\examples\with-react-router\node_modules\_react-dom@16.3.1@react-dom\cjs\react-dom-server.node.development.js:2337:22)
    at ReactDOMServerRenderer.read (D:\beidou-master\examples\with-react-router\node_modules\_react-dom@16.3.1@react-dom\cjs\react-dom-server.node.development.js:2311:19)
name: 'unhandledRejectionError'
pid: 16244
hostname: PC-201709041130

**Comment by njugray** [comment]
1. 区分下浏 fetch 在浏览器和服务端区别:
**Browser**
`fetch('/api/foo.json')` , 使用相对路径, 会在当前页面的域名下寻址
**Node**
`fetch('/api/foo.json')` 非法路径, 对服务端而言, 没有所谓的 **当前页面**

2. 上述代码我理解你的意图实在挂载前读取数据. fetch操作异步执行, 在服务端是无意义的(`renderToString`的过程是完全同步的), 服务端发送了请求也无法取得结果,  这种操作建议放在 didMount后.  如果是需要在服务端渲染的出的数据,  在进行渲染前, 预先准备好数据
